manala:
    description: Java
    sync:
      - ../.github/workflows/auto-merge.yml .github/workflows/auto-merge.yml
      - ../.github/workflows/pr-check.yml .github/workflows/pr-check.yml
      - ../.github/workflows/release.yml .github/workflows/release.yml
      - ../.releaserc .releaserc
      - .gitignore.tmpl .gitignore
      - .editorconfig
      - ../.gitattributes .gitattributes
      - ../.manala.yaml.tmpl .manala.yaml.tmpl

# Save variable (manala delete original config vars under manala key)
recipe_save: dev.cpp

gitignore: ''
