manala:
    description: Java
    sync:
        # CI / CD
        - ../.github/workflows/auto-merge.yaml .github/workflows/auto-merge.yaml
        - ../.github/workflows/pr-check.yaml .github/workflows/pr-check.yaml
        - ../.github/workflows/release.yaml .github/workflows/release.yaml
        - ../.github/workflows/labels.yaml .github/workflows/labels.yaml
        - ../.github/lock.yaml .github/lock.yaml
        - ../.github/labels.yaml .github/labels.yaml
        - ../.github/stale.yaml .github/stale.yaml
        - ../.github/PULL_REQUEST_TEMPLATE.md .github/PULL_REQUEST_TEMPLATE.md
        - ../.github/wip.yaml .github/wip.yaml
        - ../.releaserc.tmpl .releaserc
        # gitignore
        - .gitignore.tmpl .gitignore
        - .editorconfig
        - .vscode/
        # base
        - ../.gitattributes .gitattributes
        - ../.manala.yaml.tmpl.dist .manala.yaml.tmpl.dist


# Save variable (manala delete original config vars under manala key)
recipe_save: dev.cpp

gitignore: ''

semantic_release:
    # https://github.com/semantic-release/exec#usage
    exec: ~
    # check https://github.com/semantic-release/github#assets
    github: ~
