manala:
    description: Java
    sync:
      # CI / CD
      - ../.github/workflows/auto-merge.yaml .github/workflows/auto-merge.yaml
      - ../.github/workflows/pr-check.yaml .github/workflows/pr-check.yaml
      - ../.github/workflows/release.yaml .github/workflows/release.yaml
      - ../.github/PULL_REQUEST_TEMPLATE.md .github/PULL_REQUEST_TEMPLATE.md
      - ../.github/wip.yml .github/wip.yml
      - ../.releaserc .releaserc
      # gitignore
      - .gitignore.tmpl .gitignore
      - .editorconfig
      - .vscode/
      # base
      - ../.gitattributes .gitattributes
      - ../.manala.yaml.tmpl.dist .manala.yaml.tmpl.dist


# Save variable (manala delete original config vars under manala key)
recipe_save: dev.cpp

gitignore: ''
