ansible:
    disabled: false
    inventory: ""
    playbook: ""
    sub_playbook: site.yml
    type: local
    vars:
        keyboard_mac: false
box: loic-roux-404/deb64-buster
box_update: false
box_version: null
domain: localhost
fs:
    opts:
        disabled: true
        ignored:
          - /**/.DS_Store
          - .git
          - .vagrant
          - .idea/
          - .vscode/
        rsync_auto: true
        smb_password: null
        smb_username: null
    type: rsync
git:
    org: lolo
    provider: https://github.com
network:
    dns: true
    ip: null
    ports: []
    ssl:
        cert: null
        path: /etc/ssl
    type: private
paths:
    guest: /vagrant
    host: ./
    web: ""
project_name: lolo
provider:
    opts:
        cpus: "2"
        memory: "1024"
        natdnshostresolver1: on
    type: virtualbox
vb_guest_update: false