manala:
    description: Vagrant
    sync:
        - ./
vagrant:
    # @schema {"type": "string", "minLength": 3}
    # @option {"label": "Project name (use git repo name)"}
    project_name: ~
    # @schema {"type": "string", "minLength": 3}
    # @option {"label": "Hostname"}
    domain: "localhost"
    # @schema {"type": "string"}
    box: "loic-roux-404/deb64-buster"
    # @schema {"type": "boolean"}
    vb_guest_update: false
    # @schema {"type": "boolean"}
    box_update: false
    # @schema {"type": ["null","string"]}
    box_version: ~
    git:
        # @schema {"type": "string"}
        # @option {"label": "Git username"}
        org: "loic-roux-404"
        # @schema {"type": "string"}
        provider: "https://github.com"

    paths:
        # @schema {"type": "string" }
        web: ""
        # @schema {"type": "string", "default": "./"}
        host: "./"
        # @schema {"type": "string", "default": "/vagrant"}
        guest: "/vagrant"

    network:
        # @schema {"type": "string", "format": "ipv4"}
        # @option {"label": "Enter valid machine IP(V4/V6) address"}
        ip: "192.168.33.10"
        # @schema {"enum": ["private", "public"]}
        # @option {"label": "Vagrant networking"}
        type: "private"
        dhcp: true
        # @schema {"enum": [true, false]}
        # @option {"label": "Enable local dns server"}
        dns: true
        # @schema {
        #     "definitions": {
        #         "port": {"type": "object", "$id": "#port",
        #             "additionalProperties": false,
        #             "properties": {
        #                 "guest": {"type": "integer"},
        #                 "host": {"type": "integer"},
        #                 "auto_correct":  {"type": "boolean"},
        #                 "disabled": {"type": "boolean"}
        #             }
        #          }
        #      },
        #      "items": {"$ref": "#port"}
        #  }
        ports: []
        ssl:
            # @schema {"type": "string"}
            cert: ""
            # @schema {"type": "string"}
            path: "/etc/ssl"

    ansible:
        # @schema {"type": "boolean"}
        disabled: false
        # @schema {"type": "string"}
        # @option {"label": "Playbook git repo name"}
        playbook: ""
        # @schema {"type": "string" }
        # @option {"label": "Inventory name"}
        inventory: ""
        # @schema {"enum": ["local", "classic", "worker"]}
        # @option {"label": "Vagrant ansible provisionning mode"}
        type: "local"
        # @schema {"type": "string"}
        sub_playbook: "site.yml"
        # @schema {"type": "object"}
        vars:
            keyboard_mac: false

    fs:
        # @schema {"enum": ["rsync", "nfs", "smb", "vbox"]}
        # @option {"label": "Shared folder type"}
        type: "rsync"
        opts:
            # @schema {"type": "boolean"}
            auto: true
            # @schema {"enum": [true, false]}
            # @option {"label": "Disable shared folder"}
            disabled: true
            # @schema {"type": ["null","string"]}
            smb_username: ~
            # @schema {"type": ["null","string"]}
            smb_password: ~
            # @schema {"items": {"type": "string"}}
            ignored: ["/**/.DS_Store", ".git", ".vagrant", ".idea/", ".vscode/"]

    provider:
        # @schema {"enum": ["virtualbox", "libvirt", "docker", "parallels", "vmware"]}
        # @option {"label": "Hypervisor"}
        type: "virtualbox"
        # @schema {"type": "object"}
        opts:
            natdnshostresolver1: "on"
            cpus: "2"
            memory: "1024"
