manala:
    description: Deno
    sync:
      - ../.github/workflows/auto-merge.yml .github/workflows/auto-merge.yml
      - ../.github/workflows/pr-check.yml .github/workflows/pr-check.yml
      - ../.github/workflows/release.yml .github/workflows/release.yml
      - ../.releaserc .releaserc
      - .manala/
      - .editorconfig
      - .vscode/extensions.json
      - .vscode/settings.json
      - .github/workflows/deploy.yml
      - .github/workflows/test.yml
      - ../.github/ .github/
      - ../.gitattributes .gitattributes
