manala:
    description: Deno
    sync:
      - .manala/
      - .editorconfig
      - .vscode/extensions.json
      - .vscode/settings.json
      - .github/workflows/
      - ../.github/ .github/
      - ../.gitattributes .gitattributes
