manala:
    description: Java
    sync:
      # CI / CD
      - ../.github/workflows/auto-merge.yaml .github/workflows/auto-merge.yaml
      - ../.github/workflows/pr-check.yaml .github/workflows/pr-check.yaml
      - ../.github/workflows/release.yaml .github/workflows/release.yaml
      - ../.github/workflows/labels.yaml .github/workflows/labels.yaml
      - ../.github/lock.yaml .github/lock.yaml
      - ../.github/labels.yaml .github/labels.yaml
      - ../.github/stale.yaml .github/stale.yaml
      - ../.github/PULL_REQUEST_TEMPLATE.md .github/PULL_REQUEST_TEMPLATE.md
      - ../.github/wip.yaml .github/wip.yaml
      - ../.releaserc.tmpl .releaserc
      # Docker
      - ../ops.docker/.manala/docker.mk .manala/docker.mk
      # go files
      - .gitignore.tmpl .gitignore
      - .editorconfig
      # base
      - ../.gitattributes .gitattributes
      - ../.manala.yaml.tmpl.dist .manala.yaml.tmpl.dist

gitignore: ''
semantic_release: {}
