manala:
    description: Symfony light
    sync:
      # CI / CD
      - ../.github/workflows/auto-merge.yml .github/workflows/auto-merge.yml
      - ../.github/workflows/pr-check.yml .github/workflows/pr-check.yml
      - ../.github/workflows/release.yml .github/workflows/release.yml
      - ../.github/PULL_REQUEST_TEMPLATE.md .github/PULL_REQUEST_TEMPLATE.md
      - ../.github/wip.yml .github/wip.yml
      - ../.releaserc .releaserc
      # sf files
      - .manala/make
      - .manala/mariadb
      - .manala/nginx
      - .manala/php
      - .manala/starship
      - .manala/.dockerignore
      - .manala/.gitignore
      - .manala/docker-compose.yaml.tmpl
      - .manala/Dockerfile.tmpl
      - .manala/Makefile.tmpl
      - .manala.yaml.tmpl.dist
      - Makefile.dist
      - README.md .manala/README.md

#######
# App #
#######

# @option {"label": "App name"}
# @schema {"type": "string", "pattern": "^[-a-z]+$"}
app: ~

##########
# System #
##########

system:
    nginx:
        # @option {"label": "Nginx version"}
        # @schema {"enum": [1.18]}
        version: ~
    php:
        # @option {"label": "Php version"}
        # @schema {"enum": [7.4]}
        version: ~
    nodejs:
        # @option {"label": "Nodejs version"}
        # @schema {"enum": [null, 12]}
        version: ~
    mariadb:
        # @option {"label": "MariaDB version"}
        # @schema {"enum": [null, 10.4]}
        version: ~
