manala:
    description: Symfony light
    template: .manala.yaml.tmpl.dist
    sync:
        # CI / CD
        - ../.github/workflows/auto-merge.yaml .github/workflows/auto-merge.yaml
        - ../.github/workflows/pr-check.yaml .github/workflows/pr-check.yaml
        - ../.github/workflows/release.yaml .github/workflows/release.yaml
        - ../.github/workflows/labels.yaml .github/workflows/labels.yaml
        - ../.github/lock.yaml .github/lock.yaml
        - ../.github/labels.yaml .github/labels.yaml
        - ../.github/stale.yaml .github/stale.yaml
        - ../.github/PULL_REQUEST_TEMPLATE.md .github/PULL_REQUEST_TEMPLATE.md
        - ../.github/wip.yaml .github/wip.yaml
        - ../.releaserc.tmpl .releaserc
        # sf files
        - .manala/make
        - .manala/mariadb
        - .manala/nginx
        - .manala/php
        - .manala/starship
        - .manala/.dockerignore
        - .manala/.gitignore
        - .manala/docker-compose.yaml.tmpl
        - .manala/Dockerfile.tmpl
        - .manala/Makefile.tmpl
        - Makefile.dist
        - README.md .manala/README.md

# env 
gitignore: ""
semantic_release: {}

#######
# App #
#######

# @option {"label": "App name"}
# @schema {"type": "string", "pattern": "^[-a-z]+$"}
app: ~

##########
# System #
##########

system:
    nginx:
        # @option {"label": "Nginx version"}
        # @schema {"enum": [1.18]}
        version: ~
    php:
        # @option {"label": "Php version"}
        # @schema {"enum": [7.4]}
        version: ~
    nodejs:
        # @option {"label": "Nodejs version"}
        # @schema {"enum": [null, 12]}
        version: ~
    mariadb:
        # @option {"label": "MariaDB version"}
        # @schema {"enum": [null, 10.4]}
        version: ~
