manala:
    description: Node js
    sync:
      - .manala
      - .vscode/extensions.json
      - .vscode/settings.json
      - .editorconfig
      - ../.github/ .github/
      - ../.gitattributes .gitattributes
