manala:
  description: Docker
  sync:
    - .manala/docker.mk
    - ../.gitattributes .gitattributes
    - ../.manala.yaml.tmpl .manala.yaml.tmpl
    
# Save variable (manala delete original config vars under manala key)
recipe_save: ops.docker
semantic_release: {}
