manala:
    description: Python
    sync:
      - ../dev.python/.vscode/ .vscode/
      - ../dev.python/.gitignore.tmpl .gitignore
      - ../dev.python/.manala/python.mk .manala/python.mk
      - ../dev.python/.editorconfig .editorconfig
      - ../.gitattributes .gitattributes

# Save variable (manala delete original config vars under manala key)
recipe_save: dev.python
repository_save: http://github.com/loic-roux-404/manala-recipes.git

gitignore: ''
