manala:
    description: Ansible
    sync:
      - ansible.cfg.tmpl
      - .manala/ansible.mk
      - .gitignore.tmpl
      - ../vagrant/

ansible:
    # @schema {"type": "string"}
    # @option {"label": "Default inventory"}
    default_inventory: ~
    # @schema {"enum": [false, true]}
    # @option {"label": "Keep roles in project"}
    internal_roles: False

# TODO: use this file instead of vagrant config.json

vagrant: 
    