manala:
    description: Nodejs
    sync:
      - ../.github/workflows/auto-merge.yml .github/workflows/auto-merge.yml
      - ../.github/workflows/pr-check.yml .github/workflows/pr-check.yml
      - ../.github/workflows/release.yml .github/workflows/release.yml
      - ../.releaserc .releaserc
      - .manala
      - .vscode/extensions.json
      - .vscode/settings.json
      - .editorconfig
      - ../.gitattributes .gitattributes
      - ../manala.yaml.tmpl .manala.yaml.tmpl
