name: Bump version and release

on:
    push:
        branches:
            - 'master'
            - 'beta'
            # TODO add possible additional branches

jobs:
    artifact:
        strategy:
            matrix:
                java: [ 13 ]
        env:
            MVN_FLAGS: "-Dproperties.java.version=${{ matrix.java }} -B clean"

        name: Publish - GitHub Packages
        if: >
            contains(github.event.head_commit.message, '[skip-release]') == false
            && contains(github.event.pull_request.labels.*.name, 'skip-release') == false
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: log commit in common
              run: |
                git fetch origin
                [[ $(git rev-parse --verify HEAD) = $(git rev-parse --verify origin/beta) ]] \
                 && echo 'History OK' && exit 0 || echo "history don't match with pre-release" && exit 1
            # Install sem release plugins
            - uses: actions/setup-node@v2
            - run: |
                  npm install '@semantic-release/changelog' \
                      '@semantic-release/commit-analyzer' \
                      '@semantic-release/github' \
                      '@semantic-release/release-notes-generator' \
                       semantic-release

            - name: Semantic Release
              uses: cycjimmy/semantic-release-action@v2
              id: tag_version
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

            - name: Set up JDK
              uses: actions/setup-java@v1
              with:
                  java-version: ${{ matrix.java }}

            - name: Publish artifact on GitHub Packages
              if: ${{ steps.tag_version.outputs.new_release_version }}
              run: mvn ${MVN_FLAGS} deploy -DskipTests
              env:
                  VERSION: ${{ steps.tag_version.outputs.new_release_version }}
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
